title: Thomas Step
description: This is where I share my thoughts and experiences that I encounter developing software.
google_analytics: UA-121297743-1
theme: jekyll-theme-minimal
github:
  is_user_page: true
  owner_url: https://github.com/thomasstep

collections:
  posts:
    output: true
    permalink: /blog/:title

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
