title: Thomas Step
# logo: /assets/img/logo.png
description: This is where I share my thoughts.
google_analytics: UA-121297743-1
theme: jekyll-theme-minimal
github:
  is_user_page: true
  owner_url: https://github.com/thomasstep

collections:
  posts:
    output: true
    permalink: /blog/:title

# payment_pointer: $ilp.uphold.com/kwjFN8kpmJxk

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  # - jekyll/web_monetization
