# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Thomas Step
email: thomasstep@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  I will keep myself updated on this site through posts about
  travel, programming, and any other sort of learning I do. I
  will be publicly learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thomasstep.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tmoneyfish
github_username:  thomasstep

# Build settings
markdown: kramdown
theme: jekyll-theme-prologue
remote_theme: chrisbobbe/jekyll-theme-prologue
plugins:
  - jekyll-feed

collections: [sections]

avatar: ./images/thumbnail.jpg

google_analytics: UA-121297743-1

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
