# Site
name: "ThomasStep"
description: "Writing about what I learn"
meta_description: "travel, programming, software engineering"
logo: ''
favicon: 'assets/images/thumbnail.jpg'
baseurl:
google_analytics: 'UA-121297743-1'
disqus: 'thomasstep'
mailchimp-list: 'https://thomasstep.us20.list-manage.com/subscribe/post?u=67fa638f9601377de7c051b25&amp;id=f462ea0e6e'

# Authors
authors:
  thomas:
    name: Thomas
    display_name: Thomas
    gravatar: 67037e8b9d606f5a998a70da9c0f669e
    email: thomasstep@outlook.com
    web: https://www.thomasstep.com
    twitter: https://twitter.com/tmoneyfish
    description: "Software engineer and traveler."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge
