title: Thomas Step
# logo: /assets/img/logo.png
description: This is where I share my thoughts and pictures.
google_analytics: UA-121297743-1
theme: jekyll-theme-minimal
github:
  is_user_page: true
  owner_url: https://github.com/thomasstep
